Butler/Sample/Areas/Butler/Controllers/WelcomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using ButlerCore;
using ButlerWeb.Areas.Butler.Helpers;
using ButlerWeb.Areas.Butler.Models;

namespace ButlerWeb.Areas.Butler.Controllers
{
    [Authorize]
    public class WelcomeController : Controller
    {
        //
        // GET: /Butler/Welcome/

        public ActionResult Index()
        {
            Assembly targetAssembly = Assembly.GetExecutingAssembly(); // or whichever
            List<DocumentTypeWrapper> subtypes =
                targetAssembly.GetTypes()
                              .Where(t => t.IsSubclassOf(typeof (ButlerDocument)) && t.IsPublic)
                              .Select(t => new DocumentTypeWrapper(t))
                              .ToList();

            var vm = new WelcomeViewModel();
            vm.Types = subtypes;
            foreach (DocumentTypeWrapper type in vm.Types)
            {
                type.Name = Attributes.GetName(type.Type);
            }

            return View(vm);
        }
    }
}

Butler/Sample/Areas/Butler/Views/Shared/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="large-12 columns">

        <h2>Edit</h2>
        @using (Html.BeginForm())
        {
            @Html.EditorForModel()

            <input class="btn btn-primary btn-large" type="submit" value="Spara" />
            <a href="@Url.Action("Index")">Cancel</a>
        }
        @if (ViewBag.saved != null)
        {
            <div class="alert alert-success">Saved.</div>
        }
    </div>
</div>

Butler/Sample/Areas/Butler/Views/Shared/Index.cshtml
@model GenericControllerModel
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="large-12 columns">
        <h2>@Model.Name</h2>
        <a href="@Url.Action("Edit")" class="button">New</a>

        <ul class="large-block-grid-4">
            @foreach (var entity in Model.Entities)
            {
                
                <li>
                    <a href="@Url.Action("Edit",new { Id = entity.ID })" class="entityListItem">
                        @Html.DisplayFor(e => entity)
                    </a>
                </li>
               
            }
        </ul>
    </div>
</div>

Butler/Sample/Areas/Butler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Areas/Butler/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <nav class="top-bar">
        <ul class="title-area">
            <!-- Title Area -->
            <li class="name">
                <h1><a href="@Url.Action("Index","Welcome")">Butler</a></h1>
            </li>
            <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        
        <section class="top-bar-section">
            <ul class="left">
                <li><a href="@Url.Action("Index","Welcome")">Dashboard</a></li>
                <li><a href="@Url.Action("Logout","Account")">Logout</a></li>
            </ul>
        </section>
        </nav>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>